### ISSUE TITLE
The mod isnt working for me... in option menu nothing shows up :(

### ISSUE THREAD

**Issue by rebner123** [dslake/WorldDownloader#21]
Hello, 

I really need this mod to help me with a map of mine but after following multiple, multiple tutorials exactly how it says and even trying it with different macs around my house, when I load up minecraft, log into a server and hit escape, everything is normal. There is no download map button or anything like that. Please help me! I really need this but even if I cant get it to work, the mod is a great idea and I give props to cubic for putting it together. 

Sincerly,
Rebner123

**Comment by dslake** [comment]
I can't imagine what the problem is. All you need to do is open up your jarfile with winrar, drop in the .class files from the zipfile download and delete the META-INF folder. It's been downloaded a quarter million times and I've installed it hundreds of times myself that way. Are you trying to load it with mod loader or with some other conflicting mods perhaps? Post your question in the forum and you might get other responses there.

**Comment by rebner123** [comment]
Thank you for the very quick response but I ended up getting it 5 minutes ago. What i did was compress the folder into a .zip, load it into mcpatcher and it worked like a charm :D Thanks for making such a great mod! And one more question… If I'm not op and I still need the server seed, how can i obtain it?

-Rebner123

**Comment by dslake** [comment]
You can only get the server seed if you are op, have access to the files on the server, or get it from someone who is op.
