### ISSUE TITLE
crach minecraft 1.7.2

### ISSUE THREAD

**Issue by starpc** [dslake/WorldDownloader#36]
i did what you told me to do :) bud now i get this help 

here is the log
![log](https://f.cloud.github.com/assets/6143287/1705444/2d61a05c-60de-11e3-9dec-e6281eb0c7bb.png)

**Comment by dslake** [comment]
You are using the 1.6.4 version of World Downloader with Minecraft 1.7.2. That will not work. There is no version available yet for 1.7.2 due to missing re-obfuscation tools from MCP. When MCP is available for 1.7.2, I will update World Downloader. In the mean time, you can only use WDL with 1.6.4 or earlier clients.

**Comment by starpc** [comment]
oke thx
