### ISSUE TITLE
Minecraft does not have download button and not mac compatable!

### ISSUE THREAD

**Issue by Rosadoc** [dslake/WorldDownloader#51]
mine craft just keeps downloading 1.7.2 whenever i put it on wdl! The download button is missing and it is not MAC compatable!

**Comment by nairol** [comment]
If it keeps downloading 1.7.2 then you have done something wrong while installing the mod.
I can't really help you since I don't have OSX. There are however lots of people on the Minecraft Forums or Youtube that have made posts and videos how to install mods on Mac.

If you find out what you did wrong, please post it here so that we can improve the installation instructions. Thanks.

**Comment by nairol** [comment]
If this is still a problem please reopen this issue.
